parser: handle yaml version
The yaml module has the FullLoader class since version 5.1 only; handle
this gracefully at runtime.

This fixes the following error:

  AttributeError: module 'yaml' has no attribute 'FullLoader'

Reported-by: Zhifei Yang <zhifei.yang@arm.com>
Signed-off-by: Vincent Stehlé <vincent.stehle@arm.com>